[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18.x"
  NPM_VERSION = "9.x"

[functions]
  node_bundler = "esbuild"

[dev]
  autoLaunch = true
